version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_paqueteria
    environment:
      # Credenciales del administrador (usuario SYS/SYSTEM)
      ORACLE_PASSWORD: "admin123"
      # Nombre de la base de datos
      ORACLE_DATABASE: "Paqueteria"
      # Usuario de aplicación con privilegios DBA
      APP_USER: "admin"
      APP_USER_PASSWORD: "admin123"
    ports:
      - "1521:1521"   # Puerto estándar Oracle Database
      - "5500:5500"   # Oracle Enterprise Manager Express
    volumes:
      - oracle_data:/opt/oracle/oradata  # Persistencia de datos
    restart: always

volumes:
  oracle_data:
    driver: local
